### ISSUE TITLE
Getting duplicate classes issue while adding gradle dependency of streamr

### ISSUE THREAD

**Issue by Maximum21** [streamr-dev/streamr-client-java#120] opened 2021-01-19 22:02 UTC
Duplicate class org.iq80.leveldb.CompressionType found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.DB found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.DBComparator found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.DBException found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.DBFactory found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.DBIterator found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.Logger found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.Options found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.Range found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.ReadOptions found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.Snapshot found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.WriteBatch found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)
Duplicate class org.iq80.leveldb.WriteOptions found in modules jetified-leveldb-api-0.7 (org.iq80.leveldb:leveldb-api:0.7) and jetified-leveldbjni-all-1.18.3 (org.ethereum:leveldbjni-all:1.18.3)

this is the exception i am getting by just adding maven and dependency in build.gradle files according to the given instructions on git repository.

**Comment by kare** [comment] 2021-01-20 11:17
@Maximum21 What version of the client you are using? I recommend version 2.0.2

Sound like you have a clash from a transitive dependency leveldb.

You may want to exclude it in `build.gradle`.

https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

> _Example 4. Excluding a transitive dependency for a particular dependency declaration_
> ```
> dependencies {
>     implementation('commons-beanutils:commons-beanutils:1.9.4') {
>         exclude group: 'commons-collections', module: 'commons-collections'
>     }
> }
> ```

Or you may want to try out a development version from master branch. However, development version is currently under heavy development and may not work for your needs.

**Comment by Maximum21** [comment] 2021-01-20 18:33
implementation ('com.streamr:client:2.0.0'){
        exclude group: 'org.iq80.leveldb:leveldb-api:0.7', module:'jetified-leveldb-api-0.7'
    }

implementation ('com.streamr:client:2.0.0'){
        exclude group: 'org.iq80.leveldb:leveldb-api:0.7', module:'org.iq80.leveldb:leveldb-api:0.7'
    }

implementation ('com.streamr:client:2.0.0'){
        exclude group: 'org.ethereum:leveldbjni-all:1.18.3', module:'jetified-leveldbjni-all-1.18.3'
    }

i have tried all these solutions but its not working i am getting same error again and again. kindly get back to me if i am doing anything wrong here kindly tell me. im on  a tight schedule here.

**Comment by Maximum21** [comment] 2021-01-20 18:35
> @Maximum21 What version of the client you are using? I recommend version 2.0.2
> 
> Sound like you have a clash from a transitive dependency leveldb.
> 
> You may want to exclude it in `build.gradle`.
> 
> https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html
> 
> > _Example 4. Excluding a transitive dependency for a particular dependency declaration_
> > ```
> > dependencies {
> >     implementation('commons-beanutils:commons-beanutils:1.9.4') {
> >         exclude group: 'commons-collections', module: 'commons-collections'
> >     }
> > }
> > ```
> 
> Or you may want to try out a development version from master branch. However, development version is currently under heavy development and may not work for your needs.

i have used this on version 2.0.2 also but it shows same errors.

**Comment by kare** [comment] 2021-01-21 09:54
Unfortunately I'm unable to reproduce your error. This configuration will remove leveldb transitive dependency.
```
implementation('com.streamr:client:2.0.2') {
	exclude group: 'org.iq80.leveldb', module: 'leveldb'
}
```
Note that `exclude` directive is without version.

**Comment by Maximum21** [comment] 2021-01-21 23:34
@kare hey thanks it solved my issue, Also can you help me with one more thing actually i am trying to publish data on stream but for that when i try to get Ethereum Authentication method it requires a private key. so do i have to use my own custom private key or it can be generated from the portal or its the address that is mentioned on uper right corner of the streamr portal.

**Comment by fonty1** [comment] 2021-01-22 07:56
The private key means any Ethereum Private Key. In the JS client there is a convenience method to create one, but I see that doesn't exist in the Java client at this time unfortunately.

A quick way to get a private key is to go into Metamask and click account details, then, export private key.

Thanks for helping out @kare - I will close this issue as solved! 🎉

**Closed** 2021-01-22 07:56 UTC
